src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Entity\User;
use Cocur\Slugify\Slugify;
use App\Repository\AdRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=AdRepository::class)
 * 
 * 
 * cycle de vie de l'entité
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"title"},
 * message = "Une autre annonce possede deja le même titre, veuillez le modifier!"
 * )
 */
class Ad
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, minMessage="Le titre doit faire plus de 10 caractéres",maxMessage="Le titre doit faire moins de 255 caractére")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="L'introduction doit faire plus de 20 caractéres")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="L'introduction doit faire plus de 20 caractéres")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\Column(type="integer")
     */
    private $rooms;

    /**
     * @ORM\OneToMany(targetEntity=Image::class, mappedBy="ad", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $images;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="ads")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=Booking::class, mappedBy="ad")
     */
    private $bookings;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="ad", orphanRemoval=true)
     */
    private $comments;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }


    /**
     * permet d'obtenir un tableau des jours non disponible
     * @return array
     */
    public function getNotAvailableDAys()
    {
        $notAvaillablDay = [];
        foreach($this->bookings as $booking){
            //calculer les jours entre la date d'arriver et de depart voir methode range()
            $result = range($booking->getStartDate()->getTimestamp(),
            $booking->getEndDate()->getTimestamp(),
            24 * 60 * 60 
        );

        $days = array_map(function ($dayTimstamp){
            return new \DateTime(date('Y-m-d', $dayTimstamp));
        }, $result);

        $notAvaillablDay = array_merge($notAvaillablDay, $days);

        }

        return $notAvaillablDay;
    }

    /**
     * look if user have comment this ad
     * @param User $author
     * @return Comment|null
     * 
     */

    public function getCommentFromUser(User $author){
        foreach($this->comments->toArray() as $comment){
        if ($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }

    /**
     * moyenne des avis
     * @return float
     */
    public function getAverageRating(){

        $sum = array_reduce($this->comments->toArray(),function($total,$comment){
            return $total + $comment->getRating();
        },0) ;
    
        if($this->comments->count()>0) return $sum/$this->comments->count();

        return 0;
    }


    /**
     * init slug 
     * 
     * annotation du cycle de vie
     * avant la creation
     * @ORM\PrePersist
     * avant la mise a jours
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function  intializeSlug(){
        if(empty($this->slug)){
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title) ;
        }
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection|Image[]
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images[] = $image;
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->contains($image)) {
            $this->images->removeElement($image);
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|Booking[]
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings[] = $booking;
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->contains($booking)) {
            $this->bookings->removeElement($booking);
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->contains($comment)) {
            $this->comments->removeElement($comment);
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }
}

src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Stmt\Return_;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=BookingRepository::class)
 * 
 * Exiplique a doctrine que l'entités doit gerer son cycle de vie
 * @ORM\HasLifecycleCallbacks()
 */
class Booking
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $booker;

    /**
     * @ORM\ManyToOne(targetEntity=Ad::class, inversedBy="bookings")
     * @ORM\JoinColumn(nullable=false)
     */
    private $ad;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface",message="attention la date doit etre au bon format")
     * @Assert\GreaterThan("today", message="la date d'arriver doit etre supperieur a la date d'aujourd'hui", groups={"front"})
     */
    private $startDate;

    /**
     * @ORM\Column(type="datetime")
     * @Assert\Type("\DateTimeInterface",message="attention la date doit etre au bon format")
     * @Assert\GreaterThan(propertyPath = "startDate", message="la date de depart ne peut pas etre inferieur a la date d'arrivée saucisse !")
     */
    private $endDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createAt;

    /**
     * @ORM\Column(type="float")
     */
    private $amount;

    /**
     * @ORM\Column(type="text", nullable=true)
     * 
     */
    private $comment;


    /**
     * permet de recuperer un tableau des journnéés qui corespondes a ma resevation
     * @return array
     */
    public function getDays()
    {
        $reslut = range($this->getStartDate()->getTimestamp(),
        $this->getEndDate()->getTimestamp(),
         24 * 60 * 60);

        $days = array_map(function($dayTimesStamp){
            return new \DateTime(date('Y-m-d', $dayTimesStamp));
        }, $reslut);

        return $days;
    }



    /**
     * regarder si les dates sont disponibles
     * @return bool
     */
    public function isBookingDates()
    {

        $formatDay = function($day){
            return $day->format('Y-m-d');
        };

        //connaitre les dates impossible 
        $notAvailableDays = $this->ad->getNotAvailableDAys();

        //comparer avec les dates choisis
        $bookingDays = $this->getDays();

        //tableau qui convertit les timstapm e, chaine de carac 
        $days = array_map($formatDay,$bookingDays);

        //tableau qui convertit les timstamp, chaine de carac 
        $NotAvailable = array_map($formatDay,$notAvailableDays);

        foreach($days as $day){
            if (array_search($day, $NotAvailable) !== false) return false;
        }
        return true;
    }
        


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBooker(): ?User
    {
        return $this->booker;
    }

    public function setBooker(?User $booker): self
    {
        $this->booker = $booker;

        return $this;
    }

    public function getAd(): ?Ad
    {
        return $this->ad;
    }

    public function setAd(?Ad $ad): self
    {
        $this->ad = $ad;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->startDate;
    }

    public function setStartDate(\DateTimeInterface $startDate): self
    {
        $this->startDate = $startDate;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->endDate;
    }

    public function setEndDate(\DateTimeInterface $endDate): self
    {
        $this->endDate = $endDate;

        return $this;
    }

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->createAt;
    }

    public function setCreateAt(\DateTimeInterface $createAt): self
    {
        $this->createAt = $createAt;

        return $this;
    }

    public function getAmount(): ?float
    {
        return $this->amount;
    }

    public function setAmount(float $amount): self
    {
        $this->amount = $amount;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(?string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }


    /**
     * Callback appeller a chaque creation de resa ou a chaque mise a jour  
     * @ORM\PrePersist
     * @Orm\PreUpdate
     * @return void
     */
    
    public function prePersist(){
        if(empty($this->createAt)){
            $this->createAt = new \DateTime();
        }


        //prix de l'annonce
        if(empty($this->amount)){
            $this->amount = $this->getDuration() * $this->getAd()->getPrice();
        }
    }

    /**
     * recupere la durée du sejour
     */
    public function getDuration(){
        //diff methode date time renvoie la diff entre deux dates det type date interavle

        $diff = $this->endDate->diff($this->createAt);
        return $diff->days;
    }
}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use App\Form\AbstractUtilsType;
use App\Form\dataTransformer\FrenchToDateTimeTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractUtilsType
{


    private $transformer;


    public function __construct(FrenchToDateTimeTransformer $tranforme)
    {
        $this->transformer = $tranforme;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        
            ->add('startDate', TextType::class, $this->getConfiguration("Date d'arrivée","Votre date d'arrivée"))
            ->add('endDate', TextType::class, $this->getConfiguration("Date de depart", "Votre date de départ"))
            ->add('comment', TextareaType::class, $this->getConfiguration(false,"Si vous avez un commentaire n'hétez pas à nous en faire part !",["required" => false]))
        ;


        $builder->get('startDate')->addModelTransformer($this->transformer);
        $builder->get('endDate')->addModelTransformer($this->transformer);

    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
            //possiblilité de noter les groupes de validation
            'Validation_groups' => ["Default", "front"]
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Ad;
use App\Entity\Booking;
use App\Entity\Comment;
use App\Form\BookingType;
use App\Form\CommentType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;


class BookingController extends AbstractController
{
    /**
     * @Route("/ads/{slug}/book", name="booking_create")
     * @IsGranted("ROLE_USER")
     */
    public function book(Ad $ad, Request $req, EntityManagerInterface $man)
    {

        $booking = new Booking();
        $form = $this->createForm(BookingType::class,$booking,[
            'Validation_groups' => ["Default","front"]
        ]);

        $form->handleRequest($req);
        if($form->isSubmitted() && $form->isValid()){

            $user = $this->getUser();
            $booking->setBooker($user);
            $booking->setAd($ad);
            
            //si les date ne sont pas disponible on stop est on renvoi
            if(!$booking->isBookingDates()){
                $this->addFlash('warning', "Les dates que vous avez choisie ne sont pas disponible");
                
            }else{
                $man->persist($booking);
                $man->flush();
                return $this->redirectToRoute('booking_show', [
                    'id'=> $booking->getId(),
                    'success'=> true
                ]);
            }
            
        }


        return $this->render('booking/book.html.twig',[
            'ad' => $ad,
            'form' => $form->createView()
        ]);
    }


    /**
     * @Route("/booking/{id}", name="booking_show")
     * @IsGranted("ROLE_USER")
     * @param Booking $booking
     * @param Request $req
     * @param EntityManagerInterface $man
     * @return response
     */
    public function bookShow(Booking $booking,Request $req,EntityManagerInterface $man)
    {

        $comment = new Comment();

        $form = $this->createForm(CommentType::class, $comment);

        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){

            $comment->setAd($booking->getAd())
                    ->setAuthor($this->getUser());

            $man->persist($comment);
            $man->flush();
            
            $this->addFlash('success', 'Commentaire ajouter avec succes ! ');
        }


        return $this->render('booking/booking_show.html.twig',[
            'booking' => $booking,
            'form' => $form->createView()
        ]);
    }
}

templates/booking/book.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réserver l'annonce : <em>{{ad.title}} !</em> {% endblock %}

{% block stylesheets %}
    {{parent()}}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.standalone.min.css">

{% endblock %}



{% form_theme form 'ad/_collection.html.twig' %}

{% block body %}

<div class="container">
    <h1>Réservez pour l'annonce : {{ ad.title }}</h1>
    <p>
        Vous êtes sur le point de resever le bien de <strong> {{ad.author.fullName}} </strong>, dite nous tout, on s'occupe du reste !
    </p>

    {{ form_start(form)}}
    {# {{ dump() }} #}
    <div class="alert alert-ligth">
    <h4>Commencer par nous dire quelles dates vous interressent !</h4>
        <div class="row">
            <div class="col">
                {{form_row(form.startDate)}}
            </div>
            <div class="col">
                {{form_row(form.endDate)}}
            </div>
        </div>
    </div>
    <h4 class="mt-2">Montant du séjour : <sapn id="amout">.....</sapn> &euro;</h4>
    <span id="days">0</span> nuit(s) à {{ad.price | number_format(2,',',' ')}} &euro; par nuit.

    <h2>Vous avez un Commentaire ?</h2>
    {{form_row(form.comment)}}
    

    <h4 class="mt-2">Vous avez términé !</h4>
    <p>Vacance de rêve ? Hébergement pour le boulot ? Peu importe, on est avec vous !</p>


    <button type="submit" class="btn btn-success">Je reserve !</button>
    
    {{ form_end(form)}}
    
</div>


{% endblock %}



{% block javascripts %}

<script src="/js/ad.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.8.0/js/bootstrap-datepicker.min.js"></script>

<script>


    $(document).ready(function(){
        $('#booking_startDate, #booking_endDate').datepicker({
            format: 'dd/mm/yyyy',
            datesDisabled: [
                {% for day in ad.notAvailableDAys %}
                "{{ day.format('d/m/Y') }}",
                {% endfor %}
            ],
            startDate: new Date()
        });

            $('#booking_startDate, #booking_endDate').on('change',calculAmount)

    });



function calculAmount(){

    const endDate = new Date(
        $('#booking_endDate')
        .val()
        .replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1')
        );
    console.log(endDate);

    const startDate = new Date(
        $('#booking_startDate')
        .val()
        .replace(/(\d+)\/(\d+)\/(\d{4})/, '$3-$2-$1')
        );
    console.log(startDate);

    if( startDate && endDate && startDate < endDate){
        const DATE_TIME = 24 * 60 * 60 * 1000;
        const intervale = endDate.getTime() - startDate.getTime();
        const days = intervale / DATE_TIME;

        const amout = days * {{ ad.price }};

    $('#days').text(days);
    $('#amout').text(amout.toLocaleString('fr-FR'));

    }
}

</script>
{% endblock %}

templates/booking/booking_show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Réservation n° {{booking.id}}{% endblock %}

{% block body %}

{% set ad = booking.ad %}
{% set author = ad.author %}



    <div class="container">
        <h1 class ="my-5">Votre resérvation (n°{{booking.id}})</h1>

        {% if app.request.query.get('success') %}
        <div>
            <div class="alert alert-success">
                <h4 class="alert-heading">Bravo !</h4>
                <p>
                    Votre réservation aurprés de <strong>
                        <a href="{{path('user_show',{'slug': author.slug})}}">{{author.fullName}}</a>
                    </strong>
                    pour l'annonce 
                    <strong>
                        <a href="{{path('ads_show', {'slug' : ad.slug})}}">{{ad.title}}</a>
                    </strong>
                    à bien été prise en compte!
                </p>
            </div>
        </div>
        {% endif %}

        <div class="row">
            <div class="col">
                <div class="alert alert-light">
                    <h2>Détails</h2>
                    <dl class="row">

                        <dt class="col-md-4">Numéro</dt>
                        <dd class="col-md-8">{{booking.id}}</dd>
                        <dt class="col-md-4">Date d'arrivée</dt>
                        <dd class="col-md-8">{{booking.startDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Date de départ</dt>
                        <dd class="col-md-8">{{booking.endDate | date('d/m/Y')}}</dd>
                        <dt class="col-md-4">Nombre de nuits</dt>
                        <dd class="col-md-8">{{booking.duration}}</dd>
                        <dt class="col-md-4">Montant total</dt>
                        <dd class="col-md-8">{{booking.amount | number_format(2,',',' ')}} &euro;</dd>
                        <dt class="col-md-4">Commentaire</dt>
                        <dd class="col-md-8">{{booking.comment | default('Aucun Commentaire')}}</dd>



                    </dl>


                    <hr>
                    <h2 class="alert-heading">Votre hôte</h2>
                    <div class="row mb-3">
                        <div class="col-3">
                            <img src="{{author.picture}}" alt="{{author.fullName}} " class="_avatar _avatar-medium">

                        </div>
                        <div class="col-9">
                            <h4>
                                <a href="{{path('user_show', {'slug': author.slug})}}">{{author.fullName}}</a>
                            </h4>
                            <span class="badge badge-primary">{{author.ads | length}} annonces </span>


                        </div>

                    </div>

                    {{author.description | raw }}

                    <a href="{{path("user_show", {'slug': author.slug})}}" class="btn btn-primary">Plus d'info sur {{ author.firstname}}</a>
                </div>
                <div class="alert alert-light" id="comment">
                    <h2 class="alert-heading">Votre avis compte !</h2>
                    {% if date() > date(booking.endDate) %}
                    {% set comment = booking.ad.getCommentFromUser(app.user) %}
                        {% if comment is not null  %}

                            <blockquote>
                                {{comment.content}}
                            </blockquote>
                            <strong>
                                Note : 
                            </strong>
                                {% include "partials/rating.html.twig" with {'rating': comment.rating} %}
                        {% else %}
                            {# display form #}
                            {{ form_start(form) }}
                            {{ form_widget(form) }}

                            <button class="btn btn-primary"> Commenter </button>
                            {{ form_end(form) }} 
                        {% endif %}
                            
                        

                    {% else %}
                    <p>Vous ne pourrait pas notter cette annonce avant la fin de votre voyages ! </p>
                        
                    {% endif %}
                </div>
            </div>

            <div class="col">

                <div class="alert alert-ligth">
                    <h2 class="alert-heading">Votre hébergement</h2>
                </div>
                <h4>
                    <a href="{{path('ads_show', {'slug' : ad.slug})}}">{{ad.title}}</a>
                </h4>

                <img src="{{ad.coverImage}}" alt="Image de {{ad.title}}" class="img-fluid">

                {{ad.content | raw}}
                <hr>

                <a href="{{path('ads_show', {'slug': ad.slug})}}" class="btn btn-primary">Voir l'annonces</a>
            </div>

        </div>

    </div>

{% endblock %}



{% block javascripts %}

<script src="/js/ad.js"></script>


{% endblock %}